server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

http:
  pool:
    base:
      max-total-connections: 5
      max-per-route-connections: 2
      connect-timeout: 1000
      request-timeout: 1000
      socket-timeout: 1000
    webhook:
      max-total-connections: 6
      max-per-route-connections: 3
      connect-timeout: 2000
      request-timeout: 2000
      socket-timeout: 2000




