server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

http:
  pool:
    base:
      max-total-connections: 20
      default-max-per-route-connections: 10
      connect-timeout: 15000
      request-timeout: 15000
      socket-timeout: 15000
      defaultKeepAliveTime: 20000
      idleConnectionWaitTime: 20000




